# Generated by Django 3.2.14 on 2022-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymDetails',
            fields=[
                ('g_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gym_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('phn_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gym_details',
                'managed': False,
            },
        ),
    ]
