# Generated by Django 3.2.14 on 2022-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssTrainer',
            fields=[
                ('ass_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ass_trainer',
                'managed': False,
            },
        ),
    ]
