# Generated by Django 3.2.14 on 2022-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymPackage',
            fields=[
                ('gp_id', models.AutoField(primary_key=True, serialize=False)),
                ('gym_id', models.IntegerField()),
                ('package', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('fee', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gym_package',
                'managed': False,
            },
        ),
    ]
