# Generated by Django 3.2.14 on 2022-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=30)),
                ('fat', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
